import React from 'react';
import { Sparkles, Bot, Clock } from 'lucide-react';
import { CardHead, Empty } from '../app/ui';
import { MockBadge } from './MockBadge';
import { SourceCitation } from './SourceCitation';

/**
 * AI comparison insights.
 * Placeholder content only — the Comparison Agent output will be supplied by
 * the backend later with the same ComparisonInsight shape.
 */
export const AIComparisonInsights = ({ insights = [], onViewSource }) => (
  <article className="dash-card dash-reveal">
    <CardHead
      title="AI Comparison Insights"
      subtitle="Generated by the Comparison Agent and grounded in filed sources."
      right={<MockBadge label="Placeholder" />}
    />
    <div className="p-[18px] pt-1 space-y-2.5">
      {insights.length === 0 ? (
        <Empty
          Icon={Sparkles}
          title="No insights yet"
          description="Run a comparison to see agent-generated observations across the selected companies."
        />
      ) : (
        insights.map((ins, i) => (
          <div key={i} className="cmp-insight" style={{ animationDelay: `${i * 90}ms` }}>
            <span className="cmp-insight-icon">
              <Sparkles className="w-4 h-4" />
            </span>
            <div className="min-w-0 flex-1">
              <p className="text-[13.5px] leading-relaxed text-slate-700">{ins.text}</p>
              <div className="mt-2.5 flex flex-wrap items-center gap-2">
                <SourceCitation
                  source={ins.source}
                  page={ins.page}
                  onView={() => onViewSource?.(ins)}
                />
                <span className="dash-badge badge-info">
                  <Bot className="w-3 h-3 mr-1" />
                  {ins.agent}
                </span>
                <span className="text-[11.5px] text-slate-400 inline-flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {ins.timestamp}
                </span>
              </div>
            </div>
          </div>
        ))
      )}
    </div>
  </article>
);

/** Standalone sources panel for the whole comparison. */
export const ComparisonSources = ({ insights = [], onViewSource }) => (
  <article className="dash-card dash-reveal">
    <CardHead title="Sources" subtitle="Every comparison claim traced back to a filing." />
    <div className="p-[18px] pt-1 space-y-2">
      {insights.map((ins, i) => (
        <div key={i} className="dash-row">
          <span className="min-w-0 flex-1">
            <span className="block text-[13px] font-semibold text-slate-700 truncate">{ins.source}</span>
            <span className="block app-meta">{ins.page}</span>
          </span>
          <SourceCitation source="View source" onView={() => onViewSource?.(ins)} />
        </div>
      ))}
    </div>
  </article>
);
